version: '3'

services:
  ai_service:
    image: ai_service:1.1
    restart: unless-stopped
    ports:
      - 8080:8080
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 20s
      retries: 3

   
    
